ViveroMVC02/Models/Compra.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ViveroMVC02.Models
{
    public class Compra
    {
        public int CompraId { get; set; }
        public DateTime Fecha { get; set; }
        public int ProveedorId { get; set; }
        public Proveedor Proveedor { get; set; }
        public decimal Total { get; set; }
       


    }
}

ViveroMVC02/ViewModels/Compra/CompraEdiViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ViveroMVC02.ViewModels.Compra
{
    public class CompraEdiViewModels
    {

        public int CompraId { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar un Proveedor")]
        [Display(Name = @"Proveedor")]
        public int ProveedorId { get; set; }
        public List<Models.Proveedor> Proveedor { get; set; }

        //[Required(ErrorMessage = "El campo {0} es requerido")]
        //[Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar un Producto")]
        //[Display(Name = @"Producto")]
        //public int ProductoId { get; set; }
        //public List<Models.Producto> Productos { get; set; }


        //public List<Models.ItemCompra> ItemCompras { get; set; }

        //public List<Models.Kardex> Kardices { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [DataType(DataType.DateTime)]
        [MaxLength(255, ErrorMessage = "El campo {0} debe contener no más de {1} caracteres")]
        [Display(Name = @"Fecha")]

        public DateTime Fecha { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(255, ErrorMessage = "El campo {0} debe contener no más de {1} caracteres")]
        [Display(Name = @"Total")]
        public decimal Total { get; set; }





    }
}

ViveroMVC02/ViewModels/Compra/CompraListViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ViveroMVC02.ViewModels.Compra
{
    public class CompraListViewModels
    {


        [Display(Name = "Nro de Compra")]
        public int CompraId { get; set; }

        [Display(Name = "Proveedor")]
        public String Proveedor { get; set; }
        public DateTime Fecha { get; set; }
        public decimal Total { get; set; }

       




    }
}

ViveroMVC02/Controllers/ComprasController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ViveroMVC02.Classes;
using ViveroMVC02.Context;
using ViveroMVC02.Models;
using ViveroMVC02.ViewModels;
using ViveroMVC02.ViewModels.Compra;

namespace ViveroMVC02.Controllers
{
    public class ComprasController:Controller
    {

        private readonly ViveroDbContext _dbContext;
        private readonly int _registrosPorPagina = 10;
        private Listador<CompraListViewModels> _listador;

        public ComprasController()
        {
            _dbContext = new ViveroDbContext();
        }

        // GET: Clientes
        public ActionResult Index(int pagina = 1)
        {
            int totalRegistros = _dbContext.Compras.Count();

            var compras = _dbContext.Compras
                .Include(c => c.Proveedor)
                .OrderBy(p => p.CompraId)
                .Skip((pagina - 1) * _registrosPorPagina)
                .Take(_registrosPorPagina)
                .ToList();

            var comprasVm = Mapper
                .Map<List<Compra>, List<CompraListViewModels>>(compras);
            var totalPaginas = (int)Math.Ceiling((double)totalRegistros / _registrosPorPagina);
            _listador = new Listador<CompraListViewModels>()
            {
                RegistrosPorPagina = _registrosPorPagina,
                TotalPaginas = totalPaginas,
                TotalRegistros = totalRegistros,
                PaginaActual = pagina,
                Registros = comprasVm
            };


            return View(_listador);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compra compras = _dbContext.Compras.Find(id);
            if (compras == null)
            {
                return HttpNotFound();
            }
            return View(compras);
        }

        public ActionResult Create()
        {
            var comprasVm = new CompraEdiViewModels
            {
                Proveedor = CombosHelpers.GetProveedores(),
               

            };
            return View(comprasVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(CompraEdiViewModels compraVm)
        {
            if (!ModelState.IsValid)
            {
                compraVm.Proveedor = CombosHelpers.GetProveedores();
               
                return View(compraVm);
            }

            var compra = Mapper.Map<CompraEdiViewModels, Compra>(compraVm);

            if (!_dbContext.Compras.Any(ct => ct.CompraId == compra.CompraId ||
                                               ct.Fecha == compra.Fecha))
            {

                _dbContext.Compras.Add(compra);
                _dbContext.SaveChanges();
                TempData["Msg"] = "Registro agregado";

                return RedirectToAction("Index");

            }
            compraVm.Proveedor = CombosHelpers.GetProveedores();

            ModelState.AddModelError(string.Empty, "Registro repetido...");
            return View(compraVm);

        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var compra = _dbContext.Compras
                .Include(c => c.Proveedor)
                .SingleOrDefault(ct => ct.CompraId == id);
            if (compra == null)
            {
                return HttpNotFound();
            }

            var compraVm = Mapper.Map<Compra, CompraListViewModels>(compra);
            return View(compraVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            var compra = _dbContext.Compras
                .SingleOrDefault(ct => ct.CompraId == id);  
            try
            {
                _dbContext.Compras.Remove(compra);
                _dbContext.SaveChanges();
                TempData["Msg"] = "Registro eliminado";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                compra = _dbContext.Compras
                    .Include(c => c.Proveedor)
                    .SingleOrDefault(ct => ct.CompraId == id);

                var compraVm = Mapper
                    .Map<Compra, CompraListViewModels>(compra);

                ModelState.AddModelError(string.Empty, "Error al intentar dar de baja un registro");
                return View(compraVm);
            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var compra = _dbContext.Compras
                .SingleOrDefault(ct => ct.CompraId == id);
            if (compra == null)
            {
                return HttpNotFound();
            }

            CompraEdiViewModels compraVm = Mapper
                .Map<Compra, CompraEdiViewModels>(compra);
            compraVm.Proveedor = CombosHelpers.GetProveedores();
           

            return View(compraVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Edit(CompraEdiViewModels compraVm)
        {
            if (!ModelState.IsValid)
            {
                return View(compraVm);
            }

            var compra = Mapper.Map<CompraEdiViewModels, Compra>(compraVm);
            compraVm.Proveedor = CombosHelpers.GetProveedores();
            

            try
            {
                if (_dbContext.Compras.Any(ct => ct.Fecha == compra.Fecha
                                                    && ct.CompraId != compra.CompraId))
                {
                    compraVm.Proveedor = CombosHelpers.GetProveedores();
                   
                    ModelState.AddModelError(string.Empty, "Registro repetido");
                    return View(compraVm);
                }
                //TODO:Ver si existe como usuario, caso contrario darlo de alta
                //TODO:Ver si cambió el mail=>cambiar en la tabla de users.
                _dbContext.Entry(compra).State = EntityState.Modified;
                _dbContext.SaveChanges();
                TempData["Msg"] = "Registro editado";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                compraVm.Proveedor = CombosHelpers.GetProveedores();
                ModelState.AddModelError(string.Empty, "Error inesperado al intentar editar un registro");
                return View(compraVm);
            }
        }

        




    }
}

ViveroMVC02/Views/Compras/Create.cshtml
@*@model ViveroMVC02.ViewModels.ItemCompra.ItemCompraEditViewModels
@{
    ViewBag.Title = "Create";
}
<div class="container">
    <h2>Nueva Compra</h2>
    <hr />
    @using (Html.BeginForm("Create", "Compras", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.ProductoId)
            @Html.DropDownListFor(m => m.ProductoId, new SelectList(Model.Productos, "ProductoId", "NombreProducto"), "Seleccione un Producto", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Productos, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Cantidad)
            @Html.TextBoxFor(m => m.Cantidad, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Cantidad, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.PrecioUnitario)
            @Html.TextBoxFor(m => m.PrecioUnitario, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.PrecioUnitario, "", new { @class = "text-danger" })
        </div>

        
        <div class="form-group">
            @Html.LabelFor(m => m.Total)
            @Html.TextBoxFor(m => m.Total, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Total, "", new { @class = "text-danger" })
        </div>


        <div class="form-group">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <a href="@Url.Action("Index", "Compras")" class="btn btn-success">Volver</a>

        </div>
    }
</div>*@

ViveroMVC02/Views/Compras/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

ViveroMVC02/Views/Compras/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

ViveroMVC02/Views/Compras/Index.cshtml
@model ViveroMVC02.ViewModels.Listador<ViveroMVC02.ViewModels.Compra.CompraListViewModels>

@{
    ViewBag.Title = "Index";
}

<div>
    <a href="@Url.Action("Create", "Compras")" class="btn btn-primary" style="float: right">
        <i class="far fa-file-alt"></i>
        Nuevo
    </a>
    <h2>Lista de Compra</h2>
    <hr />

</div>
@if (TempData["Msg"] != null)
{
    var msg = (string)TempData["Msg"];
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Éxito!</strong> @msg.
    </div>

}
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().CompraId)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().Proveedor)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().Total)
            </th>

            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Registros.Any())
        {
            foreach (var item in Model.Registros)
            {
        <tr>
            <td>
                @Html.DisplayFor(m => item.CompraId)
            </td>
            <td>
                @Html.DisplayFor(m => item.Proveedor)
            </td>
            <td>
                @Html.DisplayFor(m => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(m => item.Total)
            </td>

            <td>
                @*<a href="@Url.Action("Edit","Compras",new{id=item.CompraId})" class="btn btn-warning"><i class="fas fa-edit"></i> Editar</a>*@
                <a href="@Url.Action("Details","Compras",new{id=item.CompraId})" class="btn btn-info"><i class="fas fa-list"></i> Detalle</a>
                <a href="@Url.Action("Delete", "Compras", new {id = item.CompraId})" class="btn btn-danger">
                    <i class="fas fa-trash-alt"></i> Borrar
                </a>

            </td>
        </tr>
            }

        }
        else
        {
            <tr>
                <td>No se agregaron Compras todavía</td>
            </tr>
        }
    </tbody>
</table>
@if (Model.Registros.Any())
{
    <span>
        <strong>@Model.TotalRegistros</strong> registros encontrados
    </span>
    <span>&nbsp;|&nbsp;</span>
    <span>
        Página <strong>@(Model.PaginaActual)</strong> de
        <strong>@Model.TotalPaginas</strong>
    </span>
    <span>&nbsp;|&nbsp;</span>
}
else
{
    <span>No hay resultados para esta búsqueda</span>
    <span>&nbsp;|&nbsp;</span>
}

@if (Model.PaginaActual > 1)
{
    @Html.ActionLink("<<", "Index", new { pagina = 1 },
        new { @class = "btn btn-sm btn-secondary" })
    <span></span>
    @Html.ActionLink("Anterior", "Index", new { pagina = Model.PaginaActual - 1 },
        new { @class = "btn btn-sm btn-secondary" })
}
else
{
    @Html.ActionLink("<<", "Index", new { pagina = 1 },
        new { @class = "btn btn-sm btn-secondary disabled" })
    <span></span>
    @Html.ActionLink("Anterior", "Index", new { pagina = 1 },
        new { @class = "btn btn-sm btn-secondary disabled" })
}
<span></span>
@if (Model.PaginaActual < Model.TotalPaginas)
{
    @Html.ActionLink("Siguiente", "Index", new { pagina = Model.PaginaActual + 1 },
        new { @class = "btn btn-sm btn-secondary" })
    <span></span>
    @Html.ActionLink(">>", "Index", new { pagina = Model.TotalPaginas },
        new { @class = "btn btn-sm btn-secondary" })
}
else
{
    @Html.ActionLink("Siguiente", "Index", new { pagina = Model.TotalPaginas - 1 },
        new { @class = "btn btn-sm btn-secondary disabled" })
    <span></span>
    @Html.ActionLink(">>", "Index", new { pagina = Model.TotalPaginas },
        new { @class = "btn btn-sm btn-secondary disabled" })
}