ViveroMVC02/Controllers/ProveedoresController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ViveroMVC02.Classes;
using ViveroMVC02.Context;
using ViveroMVC02.Models;
using ViveroMVC02.ViewModels;
using ViveroMVC02.ViewModels.Proveedor;

namespace ViveroMVC02.Controllers
{
    public class ProveedoresController:Controller
    {

        private readonly ViveroDbContext _dbContext;
        private readonly int _registrosPorPagina = 10;
        private Listador<ProveedorListViewModels> _listador;

        public ProveedoresController()
        {
            _dbContext = new ViveroDbContext();
        }

        // GET
        public ActionResult Index(int pagina = 1)
        {
            int totalRegistros = _dbContext.Proveedores.Count();

            var proveedores = _dbContext.Proveedores
                .Include(c => c.Provincia)
                .Include(c => c.Localidad)
                .OrderBy(p => p.RazonSocial)
                .Skip((pagina - 1) * _registrosPorPagina)
                .Take(_registrosPorPagina)
                .ToList();

            var provedorVm = Mapper
                .Map<List<Proveedor>, List<ProveedorListViewModels>>(proveedores);
            var totalPaginas = (int)Math.Ceiling((double)totalRegistros / _registrosPorPagina);
            _listador = new Listador<ProveedorListViewModels>()
            {
                RegistrosPorPagina = _registrosPorPagina,
                TotalPaginas = totalPaginas,
                TotalRegistros = totalRegistros,
                PaginaActual = pagina,
                Registros = provedorVm
            };


            return View(_listador);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proveedor proveedor = _dbContext.Proveedores.Find(id);
            if (proveedor == null)
            {
                return HttpNotFound();
            }
            return View(proveedor);
        }

        public ActionResult Create()
        {
            var proveedorVm = new ProveedorEditViewModels
            {
                Provincias = CombosHelpers.GetProvincia(),
                Localidades = CombosHelpers.GetLocalidades(),
               

            };
            return View(proveedorVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(ProveedorEditViewModels proveedorVm)
        {
            if (!ModelState.IsValid)
            {
                proveedorVm.Provincias = CombosHelpers.GetProvincia();
                proveedorVm.Localidades = CombosHelpers.GetLocalidades(proveedorVm.ProvinciaId);
                //clienteVm.TiposDeDocumentos = CombosHelpers.GetTipoDocumento();
                return View(proveedorVm);
            }

            var proveedor = Mapper.Map<ProveedorEditViewModels, Proveedor>(proveedorVm);

            if (!_dbContext.Proveedores.Any(ct => ct.RazonSocial == proveedor.RazonSocial ||
                                               ct.CorreoElectronico == proveedor.CorreoElectronico))
            {

                _dbContext.Proveedores.Add(proveedor);
                _dbContext.SaveChanges();
                TempData["Msg"] = "Registro agregado";

                return RedirectToAction("Index");

            }
            proveedorVm.Provincias = CombosHelpers.GetProvincia();
            proveedorVm.Localidades = CombosHelpers.GetLocalidades(proveedorVm.ProvinciaId);
            //clienteVm.TiposDeDocumentos = CombosHelpers.GetTipoDocumento();

            ModelState.AddModelError(string.Empty, "Registro repetido...");
            return View(proveedorVm);

        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var proveedor = _dbContext.Proveedores
                .Include(c => c.Provincia)
                .Include(c => c.Localidad)
                .SingleOrDefault(ct => ct.ProveedorId == id);
            if (proveedor == null)
            {
                return HttpNotFound();
            }

            var proveedorVm = Mapper.Map<Proveedor, ProveedorListViewModels>(proveedor);
            return View(proveedorVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            var proveedor = _dbContext.Proveedores
                .SingleOrDefault(ct => ct.ProveedorId == id);
            try
            {
                _dbContext.Proveedores.Remove(proveedor);
                _dbContext.SaveChanges();
                TempData["Msg"] = "Registro eliminado";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                proveedor = _dbContext.Proveedores
                    .Include(c => c.Provincia)
                    .Include(c => c.Localidad)
                    .SingleOrDefault(ct => ct.ProveedorId == id);

                var proveedorVm = Mapper
                    .Map<Proveedor, ProveedorListViewModels>(proveedor);

                ModelState.AddModelError(string.Empty, "Error al intentar dar de baja un registro");
                return View(proveedorVm);
            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var proveedor = _dbContext.Proveedores
                .SingleOrDefault(ct => ct.ProveedorId == id);
            if (proveedor == null)
            {
                return HttpNotFound();
            }

            ProveedorEditViewModels proveedorVm = Mapper
                .Map<Proveedor, ProveedorEditViewModels>(proveedor);
           proveedorVm.Provincias = CombosHelpers.GetProvincia();
           proveedorVm.Localidades = CombosHelpers.GetLocalidades(proveedorVm.ProvinciaId);

            return View(proveedorVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Edit(ProveedorEditViewModels proveedorVm)
        {
            if (!ModelState.IsValid)
            {
                return View(proveedorVm);
            }

            var proveedor = Mapper.Map<ProveedorEditViewModels, Proveedor>(proveedorVm);
            proveedorVm.Provincias = CombosHelpers.GetProvincia();
            proveedorVm.Localidades = CombosHelpers.GetLocalidades(proveedorVm.ProvinciaId);
            try
            {
                if (_dbContext.Proveedores.Any(ct => ct.RazonSocial == proveedor.RazonSocial
                                                    && ct.ProveedorId != proveedor.ProveedorId))
                {
                    proveedorVm.Provincias = CombosHelpers.GetProvincia();
                    proveedorVm.Localidades = CombosHelpers.GetLocalidades(proveedorVm.ProvinciaId);
                    ModelState.AddModelError(string.Empty, "Registro repetido");
                    return View(proveedorVm);
                }
                _dbContext.Entry(proveedor).State = EntityState.Modified;
                _dbContext.SaveChanges();
                TempData["Msg"] = "Registro editado";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                proveedorVm.Provincias = CombosHelpers.GetProvincia();
                proveedorVm.Localidades = CombosHelpers.GetLocalidades(proveedorVm.ProvinciaId);

                ModelState.AddModelError(string.Empty, "Error inesperado al intentar editar un registro");
                return View(proveedorVm);
            }
        }

        public JsonResult GetLocalidades(int provinciaId)
        {
            _dbContext.Configuration.ProxyCreationEnabled = false;
            var localidades = _dbContext.Localidades.Where(c => c.ProvinciaId == provinciaId).ToList();
            return Json(localidades, JsonRequestBehavior.AllowGet);
        }



    }
}

ViveroMVC02/Views/Proveedores/Create.cshtml
@model ViveroMVC02.ViewModels.Proveedor.ProveedorEditViewModels
@{
    ViewBag.Title = "Create";
}
<div class="container">
    <h2>Nuevo Proveedor</h2>
    <hr />
    @using (Html.BeginForm("Create", "Proveedores", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.RazonSocial)
            @Html.TextBoxFor(m => m.RazonSocial, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.RazonSocial, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.PersonaDeContacto)
            @Html.TextBoxFor(m => m.PersonaDeContacto, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.PersonaDeContacto, "", new { @class = "text-danger" })
        </div>
        @*<div class="row">*@
        @*<div class="col">*@
        @*<div class="form-group">
                @Html.LabelFor(m => m.TipoDocumentoId)
                @Html.DropDownListFor(m => m.TipoDocumentoId, new SelectList(Model.TiposDeDocumentos, "TipoDocumentoId", "Descripcion"), "Seleccione Tipo", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.TiposDeDocumentos, "", new { @class = "text-danger" })
            </div>*@
        <div class="form-group">
            @Html.LabelFor(m => m.Cuit)
            @Html.TextBoxFor(m => m.Cuit, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Cuit, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Direccion)
            @Html.TextBoxFor(m => m.Direccion, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Direccion, "", new { @class = "text-danger" })
        </div>

        @*</div>*@
        @*<div class="col">*@
        <div class="form-group">
            @Html.LabelFor(m => m.TelefonoFijo)
            @Html.TextBoxFor(m => m.TelefonoFijo, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TelefonoFijo, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.TelefonoMovil)
            @Html.TextBoxFor(m => m.TelefonoMovil, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TelefonoMovil, "", new { @class = "text-danger" })
        </div>

        @*</div>*@
        @*</div>*@

        <div class="form-group">
            @Html.LabelFor(m => m.ProvinciaId)
            @Html.DropDownListFor(m => m.ProvinciaId, new SelectList(Model.Provincias, "ProvinciaId", "NombreProvincia"), "Seleccione Provincia", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Provincias, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.LocalidadId)
            @Html.DropDownListFor(m => m.LocalidadId, new SelectList(Model.Localidades, "LocalidadId", "NombreLocalidad"), "Seleccione Localidad", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.LocalidadId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.CorreoElectronico)
            @Html.TextBoxFor(m => m.CorreoElectronico, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CorreoElectronico, "", new { @class = "text-danger" })
        </div>




        <div class="form-group">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <a href="@Url.Action("Index", "Proveedores")" class="btn btn-success">Volver</a>

        </div>
    }
</div>
@section scripts
 {
    <script>
        $(document).ready(function () {
            $("#ProvinciaId").change(function() {
                $("#LocalidadId").empty();
            });

            $("#ProvinciaId").change(function() {
                $("#LocalidadId").empty();
                $("#LocalidadId").append('<option value="0">[Seleccionar Localidad]</option>');

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetLocalidades")',
                    dataType: 'json',
                    data: {
                        ProvinciaId: $("#ProvinciaId").val()

                    },
                    success: function(Localidades) {
                        $.each(Localidades ,
                            function(i, localidad) {
                                $("#LocalidadId").append('<option value="' + localidad.LocalidadId + '">' + localidad.NombreLocalidad + '</option>');
                            });
                    },
                    error: function(ex) {
                        alert('Error al intentar cargar las Localidades.' + ex);
                    }
                });
                return false;
            });
        });

    </script>

}

ViveroMVC02/Views/Proveedores/Delete.cshtml
@model ViveroMVC02.ViewModels.Proveedor.ProveedorListViewModels
@{
    ViewBag.Title = "Delete";
}

<h2>Borrar Empleado</h2>
<hr />
@using (Html.BeginForm("Delete", "Proveedores", FormMethod.Post))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.RazonSocial)
        @Html.TextBoxFor(m => m.RazonSocial, new { @class = "form-control", @readonly = true })
    </div>
    
    <div class="col">

        <div class="form-group">
            @Html.LabelFor(m => m.Provincia)
            @Html.TextBoxFor(m => m.Provincia, new { @class = "form-control", @readonly = true })
        </div>

    </div>
    <div class="col">
        <div class="form-group">
            @Html.LabelFor(m => m.Localidad)
            @Html.TextBoxFor(m => m.Localidad, new { @class = "form-control", @readonly = true })
        </div>

    </div>
    @*</div>*@


    <div class="form-group">
        <button class="btn btn-danger" type="submit">Borrar</button>
        <a href="@Url.Action("Index", "Proveedores")" class="btn btn-success">Volver</a>

    </div>
}

ViveroMVC02/Views/Proveedores/Details.cshtml
@model ViveroMVC02.Models.Proveedor
@{
    ViewBag.Title = "Details";
}

<h2>Detalle Proveedor</h2>
<hr />
@using (Html.BeginForm("Details", "Proveedores", FormMethod.Post))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.RazonSocial)
        @Html.TextBoxFor(m => m.RazonSocial, new { @class = "form-control", autofocus = "autofocus" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PersonaDeContacto)
        @Html.TextBoxFor(m => m.PersonaDeContacto, new { @class = "form-control", autofocus = "autofocus" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Cuit)
        @Html.TextBoxFor(m => m.Cuit, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Direccion)
        @Html.TextBoxFor(m => m.Direccion, new { @class = "form-control" })
    </div>

   
    <div class="form-group">
        @Html.LabelFor(m => m.TelefonoFijo)
        @Html.TextBoxFor(m => m.TelefonoFijo, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TelefonoMovil)
        @Html.TextBoxFor(m => m.TelefonoMovil, new { @class = "form-control" })
    </div>

  
    <div class="form-group">
        @Html.LabelFor(m => m.CorreoElectronico)
        @Html.TextBoxFor(m => m.CorreoElectronico, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <a href="@Url.Action("Index", "Proveedores")" class="btn btn-success">
            <i class="fas fa-backspace"></i>
            Volver
        </a>
    </div>
}

ViveroMVC02/Views/Proveedores/Edit.cshtml
@model ViveroMVC02.ViewModels.Proveedor.ProveedorEditViewModels
@{ ViewBag.Title = "Edit"; }
<div class="container">
    <h2>Editar Proveedor</h2>
    <hr />
    @using (Html.BeginForm("Edit", "Proveedores", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.ProveedorId)
        <div class="form-group">
            @Html.LabelFor(m => m.RazonSocial)
            @Html.TextBoxFor(m => m.RazonSocial, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.RazonSocial, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.PersonaDeContacto)
            @Html.TextBoxFor(m => m.PersonaDeContacto, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.PersonaDeContacto, "", new { @class = "text-danger" })
        </div>
        @*<div class="row">*@
        <div class="col">
            <div class="form-group">
                @Html.LabelFor(m => m.Cuit)
                @Html.TextBoxFor(m => m.Cuit, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Cuit, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Direccion)
                @Html.TextBoxFor(m => m.Direccion, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Direccion, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="col">
            <div class="form-group">
                @Html.LabelFor(m => m.TelefonoFijo)
                @Html.TextBoxFor(m => m.TelefonoFijo, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.TelefonoFijo, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.TelefonoMovil)
                @Html.TextBoxFor(m => m.TelefonoMovil, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.TelefonoMovil, "", new { @class = "text-danger" })
            </div>

        </div>
        @*</div>*@

        <div class="form-group">
            @Html.LabelFor(m => m.ProvinciaId)
            @Html.DropDownListFor(m => m.ProvinciaId, new SelectList(Model.Provincias, "ProvinciaId", "NombreProvincia"), "Seleccione Provincia", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Provincias, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.LocalidadId)
            @Html.DropDownListFor(m => m.LocalidadId, new SelectList(Model.Localidades, "LocalidadId", "NombreLocalidad"), "Seleccione Localidad", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.LocalidadId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.CorreoElectronico)
            @Html.TextBoxFor(m => m.CorreoElectronico, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CorreoElectronico, "", new { @class = "text-danger" })
        </div>


        <div class="form-group">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <a href="@Url.Action("Index", "Proveedores")" class="btn btn-success">Volver</a>

        </div>}
</div>
@section scripts
 {
    <script>
        $(document).ready(function () {
            $("#ProvinciaId").change(function() {
                $("#LocalidadId").empty();
            });

            $("#ProvinciaId").change(function() {
                $("#LocalidadId").empty();
                $("#LocalidadId").append('<option value="0">[Seleccionar Localidad]</option>');

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetLocalidades")',
                    dataType: 'json',
                    data: {
                        ProvinciaId: $("#ProvinciaId").val()

                    },
                    success: function(Localidades) {
                        $.each(Localidades ,
                            function(i, localidad) {
                                $("#LocalidadId").append('<option value="' + localidad.LocalidadId + '">' + localidad.NombreLocalidad + '</option>');
                            });
                    },
                    error: function(ex) {
                        alert('Error al intentar cargar las Localidades.' + ex);
                    }
                });
                return false;
            });
        });

    </script>

}

ViveroMVC02/Views/Proveedores/Index.cshtml
@model ViveroMVC02.ViewModels.Listador<ViveroMVC02.ViewModels.Proveedor.ProveedorListViewModels>

@{
    ViewBag.Title = "Index";
}

<div>
    <a href="@Url.Action("Create", "Proveedores")" class="btn btn-primary" style="float: right">
        <i class="far fa-file-alt"></i>
        Nuevo
    </a>
    <h2>Lista de Proveedores</h2>
    <hr />

</div>
@if (TempData["Msg"] != null)
{
    var msg = (string)TempData["Msg"];
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Éxito!</strong> @msg.
    </div>

}
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().RazonSocial)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().Localidad)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().Provincia)
            </th>
            

            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Registros.Any())
        {
            foreach (var item in Model.Registros)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m => item.RazonSocial)
                    </td>
                    
                    <td>
                        @Html.DisplayFor(m => item.Localidad)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Provincia)
                    </td>

                    <td>
                        <a href="@Url.Action("Edit","Proveedores",new{id=item.ProveedorId})" class="btn btn-warning"><i class="fas fa-edit"></i> Editar</a>
                        <a href="@Url.Action("Details","Proveedores",new{id=item.ProveedorId})" class="btn btn-info"><i class="fas fa-list"></i> Detalle</a>
                        <a href="@Url.Action("Delete", "Proveedores", new {id = item.ProveedorId})" class="btn btn-danger">
                            <i class="fas fa-trash-alt"></i> Borrar
                        </a>

                    </td>
                </tr>
            }

        }
        else
        {
            <tr>
                <td>No se agregaron Proveedores todavía</td>
            </tr>
        }
    </tbody>
</table>
@if (Model.Registros.Any())
{
    <span>
        <strong>@Model.TotalRegistros</strong> registros encontrados
    </span>
    <span>&nbsp;|&nbsp;</span>
    <span>
        Página <strong>@(Model.PaginaActual)</strong> de
        <strong>@Model.TotalPaginas</strong>
    </span>
    <span>&nbsp;|&nbsp;</span>
}
else
{
    <span>No hay resultados para esta búsqueda</span>
    <span>&nbsp;|&nbsp;</span>
}

@if (Model.PaginaActual > 1)
{
    @Html.ActionLink("<<", "Index", new { pagina = 1 },
        new { @class = "btn btn-sm btn-secondary" })
    <span></span>
    @Html.ActionLink("Anterior", "Index", new { pagina = Model.PaginaActual - 1 },
        new { @class = "btn btn-sm btn-secondary" })
}
else
{
    @Html.ActionLink("<<", "Index", new { pagina = 1 },
        new { @class = "btn btn-sm btn-secondary disabled" })
    <span></span>
    @Html.ActionLink("Anterior", "Index", new { pagina = 1 },
        new { @class = "btn btn-sm btn-secondary disabled" })
}
<span></span>
@if (Model.PaginaActual < Model.TotalPaginas)
{
    @Html.ActionLink("Siguiente", "Index", new { pagina = Model.PaginaActual + 1 },
        new { @class = "btn btn-sm btn-secondary" })
    <span></span>
    @Html.ActionLink(">>", "Index", new { pagina = Model.TotalPaginas },
        new { @class = "btn btn-sm btn-secondary" })
}
else
{
    @Html.ActionLink("Siguiente", "Index", new { pagina = Model.TotalPaginas - 1 },
        new { @class = "btn btn-sm btn-secondary disabled" })
    <span></span>
    @Html.ActionLink(">>", "Index", new { pagina = Model.TotalPaginas },
        new { @class = "btn btn-sm btn-secondary disabled" })
}