ViveroMVC02/Models/Empleado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ViveroMVC02.Models
{
    public class Empleado
    {
        public int EmpleadoId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public string NroDocumento { get; set; }
        public int ProvinciaId { get; set; }
        public int LocalidadId { get; set; }
        public Provincia Provincia { get; set; }
        public Localidad Localidad { get; set; }
        public string TelefonoFijo { get; set; }
        public string TelefonoMovil { get; set; }
        public string CorreoElectronico { get; set; }


    }
}

ViveroMVC02/ViewModels/Empleado/EmpleadoEditViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ViveroMVC02.ViewModels.Empleado
{
    public class EmpleadoEditViewModels
    {

        public int EmpleadoId { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(150, ErrorMessage = "El campo {0} debe contener entre {2} and {1} caracteres", MinimumLength = 3)]
        [Display(Name = @"Nombre")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(150, ErrorMessage = "El campo {0} debe contener entre {2} and {1} caracteres", MinimumLength = 3)]
        [Display(Name = @"Apellido")]
        public string Apellido { get; set; }


        [MaxLength(255, ErrorMessage = "El campo {0} debe contener no más de {1} caracteres")]
        [Display(Name = @"Dirección")]
        public string Direccion { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar una Provincia")]
        [Display(Name = @"Provincia")]
        public int ProvinciaId { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar una Localidad")]
        [Display(Name = @"Localidad")]

        public int LocalidadId { get; set; }
        public List<Models.Provincia> Provincias { get; set; }
        public List<Models.Localidad> Localidades { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        [MaxLength(255, ErrorMessage = "El campo {0} debe contener no más de {1} caracteres")]
        [Display(Name = @"Numero de documento")]

        public String NroDocumento { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [DataType(DataType.EmailAddress)]
        [MaxLength(255, ErrorMessage = "El campo {0} debe contener no más de {1} caracteres")]
        [Display(Name = @"Mail")]
        public string CorreoElectronico { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(255, ErrorMessage = "El campo {0} debe contener no más de {1} caracteres")]
        [Display(Name = @"Nro. De telefono movil")]
        public string TelefonoMovil { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(255, ErrorMessage = "El campo {0} debe contener no más de {1} caracteres")]
        [Display(Name = @"Nro. De telefono fijo")]
        public string TelefonoFijo { get; set; }




    }

}

ViveroMVC02/ViewModels/Empleado/EmpleadoListViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ViveroMVC02.ViewModels.Empleado
{
    public class EmpleadoListViewModels
    {

        public int EmpleadoId { get; set; }

        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Display(Name = "Apellido")]
        public string Apellido { get; set; }

        [Display(Name = "Provincia")]
        public string Provincia { get; set; }

        public string Localidad { get; set; }

    }
}

ViveroMVC02/Controllers/EmpleadosController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ViveroMVC02.Classes;
using ViveroMVC02.Context;
using ViveroMVC02.Models;
using ViveroMVC02.ViewModels;
using ViveroMVC02.ViewModels.Empleado;

namespace ViveroMVC02.Controllers
{
    public class EmpleadosController:Controller
    {

        private readonly ViveroDbContext _dbContext;
        private readonly int _registrosPorPagina = 10;
        private Listador<EmpleadoListViewModels> _listador;

        public EmpleadosController()
        {
            _dbContext = new ViveroDbContext();
        }

       
        public ActionResult Index(int pagina = 1)
        {
            int totalRegistros = _dbContext.Empleados.Count();

            var empleados = _dbContext.Empleados
                .Include(c => c.Provincia)
                .Include(c => c.Localidad)
                .OrderBy(c => c.Nombre)
                .Skip((pagina - 1) * _registrosPorPagina)
                .Take(_registrosPorPagina)
                .ToList();

            var empleadoVm = Mapper
                .Map<List<Empleado>, List<EmpleadoListViewModels>>(empleados);
            var totalPaginas = (int)Math.Ceiling((double)totalRegistros / _registrosPorPagina);
            _listador = new Listador<EmpleadoListViewModels>()
            {
                RegistrosPorPagina = _registrosPorPagina,
                TotalPaginas = totalPaginas,
                TotalRegistros = totalRegistros,
                PaginaActual = pagina,
                Registros = empleadoVm
            };


            return View(_listador);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = _dbContext.Empleados.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        public ActionResult Create()
        {
            var empleadoVm = new EmpleadoEditViewModels
            {
                Provincias = CombosHelpers.GetProvincia(),
                Localidades = CombosHelpers.GetLocalidades(),
            };
            return View(empleadoVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(EmpleadoEditViewModels empleadoVm)
        {
            if (!ModelState.IsValid)
            {
                empleadoVm.Provincias = CombosHelpers.GetProvincia();
                empleadoVm.Localidades = CombosHelpers.GetLocalidades(empleadoVm.ProvinciaId);
                return View(empleadoVm);
            }

            var empleado = Mapper.Map<EmpleadoEditViewModels, Empleado>(empleadoVm);

            if (!_dbContext.Empleados.Any(ct => ct.Nombre == empleado.Nombre ||
                                               ct.CorreoElectronico == empleado.CorreoElectronico))
            {

                _dbContext.Empleados.Add(empleado);
                _dbContext.SaveChanges();
                TempData["Msg"] = "Registro agregado";

                return RedirectToAction("Index");

            }
            empleadoVm.Provincias = CombosHelpers.GetProvincia();
            empleadoVm.Localidades = CombosHelpers.GetLocalidades(empleadoVm.ProvinciaId);
            //clienteVm.TiposDeDocumentos = CombosHelpers.GetTipoDocumento();

            ModelState.AddModelError(string.Empty, "Registro repetido...");
            return View(empleadoVm);

        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var empleado = _dbContext.Empleados
                .Include(c => c.Provincia)
                .Include(c => c.Localidad)
                .SingleOrDefault(ct => ct.EmpleadoId == id);
            if (empleado == null)
            {
                return HttpNotFound();
            }

            var empleadoVm = Mapper.Map<Empleado, EmpleadoListViewModels>(empleado);
            return View(empleadoVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            var empleado = _dbContext.Empleados
                .SingleOrDefault(ct => ct.EmpleadoId == id);
            try
            {
                _dbContext.Empleados.Remove(empleado);
                _dbContext.SaveChanges();
                TempData["Msg"] = "Registro eliminado";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                empleado = _dbContext.Empleados
                    .Include(c => c.Provincia)
                    .Include(c => c.Localidad)
                    .SingleOrDefault(ct => ct.EmpleadoId == id);

                var empleadoVm = Mapper
                    .Map<Empleado, EmpleadoListViewModels>(empleado);

                ModelState.AddModelError(string.Empty, "Error al intentar dar de baja un registro");
                return View(empleadoVm);
            }
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var empleado = _dbContext.Empleados
                .SingleOrDefault(ct => ct.EmpleadoId == id);
            if (empleado == null)
            {
                return HttpNotFound();
            }

            EmpleadoEditViewModels empleadoVm = Mapper
                .Map<Empleado, EmpleadoEditViewModels>(empleado);
            empleadoVm.Provincias = CombosHelpers.GetProvincia();
            empleadoVm.Localidades = CombosHelpers.GetLocalidades(empleadoVm.ProvinciaId);
            return View(empleadoVm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Edit(EmpleadoEditViewModels empleadoVm)
        {
            if (!ModelState.IsValid)
            {
                return View(empleadoVm);
            }

            var empleado = Mapper.Map<EmpleadoEditViewModels, Empleado>(empleadoVm);
            empleadoVm.Provincias = CombosHelpers.GetProvincia();
            empleadoVm.Localidades = CombosHelpers.GetLocalidades(empleadoVm.ProvinciaId);
            try
            {
                if (_dbContext.Empleados.Any(ct => ct.Nombre == empleado.Nombre
                                                    && ct.EmpleadoId != empleado.EmpleadoId))
                {
                   empleadoVm.Provincias = CombosHelpers.GetProvincia();
                   empleadoVm.Localidades = CombosHelpers.GetLocalidades(empleadoVm.ProvinciaId);
                    ModelState.AddModelError(string.Empty, "Registro repetido");
                    return View(empleadoVm);
                }
                _dbContext.Entry(empleado).State = EntityState.Modified;
                _dbContext.SaveChanges();
                TempData["Msg"] = "Registro editado";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                empleadoVm.Provincias = CombosHelpers.GetProvincia();
                empleadoVm.Localidades = CombosHelpers.GetLocalidades(empleadoVm.ProvinciaId);
                ModelState.AddModelError(string.Empty, "Error inesperado al intentar editar un registro");
                return View(empleadoVm);
            }
        }

        public JsonResult GetLocalidades(int provinciaId)
        {
            _dbContext.Configuration.ProxyCreationEnabled = false;
            var localidades = _dbContext.Localidades.Where(c => c.ProvinciaId == provinciaId).ToList();
            return Json(localidades, JsonRequestBehavior.AllowGet);
        }







    }
}

ViveroMVC02/Views/Empleados/Create.cshtml
@model ViveroMVC02.ViewModels.Empleado.EmpleadoEditViewModels
@{
    ViewBag.Title = "Create";
}
<div class="container">
    <h2>Nuevo Empleado</h2>
    <hr />
    @using (Html.BeginForm("Create", "Empleados", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.Nombre)
            @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.Nombre, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Apellido)
            @Html.TextBoxFor(m => m.Apellido, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.Apellido, "", new { @class = "text-danger" })
        </div>
        @*<div class="row">*@
        @*<div class="col">*@
        @*<div class="form-group">
                @Html.LabelFor(m => m.TipoDocumentoId)
                @Html.DropDownListFor(m => m.TipoDocumentoId, new SelectList(Model.TiposDeDocumentos, "TipoDocumentoId", "Descripcion"), "Seleccione Tipo", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.TiposDeDocumentos, "", new { @class = "text-danger" })
            </div>*@
        <div class="form-group">
            @Html.LabelFor(m => m.NroDocumento)
            @Html.TextBoxFor(m => m.NroDocumento, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.NroDocumento, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Direccion)
            @Html.TextBoxFor(m => m.Direccion, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Direccion, "", new { @class = "text-danger" })
        </div>

        @*</div>*@
        @*<div class="col">*@
        <div class="form-group">
            @Html.LabelFor(m => m.TelefonoFijo)
            @Html.TextBoxFor(m => m.TelefonoFijo, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TelefonoFijo, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.TelefonoMovil)
            @Html.TextBoxFor(m => m.TelefonoMovil, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.TelefonoMovil, "", new { @class = "text-danger" })
        </div>

        @*</div>*@
        @*</div>*@

        <div class="form-group">
            @Html.LabelFor(m => m.ProvinciaId)
            @Html.DropDownListFor(m => m.ProvinciaId, new SelectList(Model.Provincias, "ProvinciaId", "NombreProvincia"), "Seleccione Provincia", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Provincias, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.LocalidadId)
            @Html.DropDownListFor(m => m.LocalidadId, new SelectList(Model.Localidades, "LocalidadId", "NombreLocalidad"), "Seleccione Localidad", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.LocalidadId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.CorreoElectronico)
            @Html.TextBoxFor(m => m.CorreoElectronico, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CorreoElectronico, "", new { @class = "text-danger" })
        </div>

       




        <div class="form-group">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <a href="@Url.Action("Index", "Empleados")" class="btn btn-success">Volver</a>

        </div>
    }
</div>
@section scripts
 {
    <script>
        $(document).ready(function () {
            $("#ProvinciaId").change(function() {
                $("#LocalidadId").empty();
            });

            $("#ProvinciaId").change(function() {
                $("#LocalidadId").empty();
                $("#LocalidadId").append('<option value="0">[Seleccionar Localidad]</option>');

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetLocalidades")',
                    dataType: 'json',
                    data: {
                        ProvinciaId: $("#ProvinciaId").val()

                    },
                    success: function(Localidades) {
                        $.each(Localidades ,
                            function(i, localidad) {
                                $("#LocalidadId").append('<option value="' + localidad.LocalidadId + '">' + localidad.NombreLocalidad + '</option>');
                            });
                    },
                    error: function(ex) {
                        alert('Error al intentar cargar las Localidades.' + ex);
                    }
                });
                return false;
            });
        });

    </script>

}

ViveroMVC02/Views/Empleados/Delete.cshtml
@model ViveroMVC02.ViewModels.Empleado.EmpleadoListViewModels
@{
    ViewBag.Title = "Delete";
}

<h2>Borrar Empleado</h2>
<hr />
@using (Html.BeginForm("Delete", "Empleados", FormMethod.Post))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(m => m.Nombre)
        @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control", @readonly = true })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Apellido)
        @Html.TextBoxFor(m => m.Apellido, new { @class = "form-control", @readonly = true })
    </div>
    @*<div class="row">*@
    <div class="col">

        <div class="form-group">
            @Html.LabelFor(m => m.Provincia)
            @Html.TextBoxFor(m => m.Provincia, new { @class = "form-control", @readonly = true })
        </div>

    </div>
    <div class="col">
        <div class="form-group">
            @Html.LabelFor(m => m.Localidad)
            @Html.TextBoxFor(m => m.Localidad, new { @class = "form-control", @readonly = true })
        </div>

    </div>
    @*</div>*@


    <div class="form-group">
        <button class="btn btn-danger" type="submit">Borrar</button>
        <a href="@Url.Action("Index", "Empleados")" class="btn btn-success">Volver</a>

    </div>
}

ViveroMVC02/Views/Empleados/Details.cshtml
@model ViveroMVC02.Models.Empleado
@{
    ViewBag.Title = "Details";
}

<h2>Detalle Proveedor</h2>
<hr />
@using (Html.BeginForm("Details", "Empleados", FormMethod.Post))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.Nombre)
        @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control", autofocus = "autofocus" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Apellido)
        @Html.TextBoxFor(m => m.Apellido, new { @class = "form-control", autofocus = "autofocus" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.NroDocumento)
        @Html.TextBoxFor(m => m.NroDocumento, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Direccion)
        @Html.TextBoxFor(m => m.Direccion, new { @class = "form-control" })
    </div>

    @*</div>*@
    @*<div class="col">*@
    <div class="form-group">
        @Html.LabelFor(m => m.TelefonoFijo)
        @Html.TextBoxFor(m => m.TelefonoFijo, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TelefonoMovil)
        @Html.TextBoxFor(m => m.TelefonoMovil, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.TelefonoMovil, "", new { @class = "text-danger" })
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.CorreoElectronico)
        @Html.TextBoxFor(m => m.CorreoElectronico, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CorreoElectronico, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <a href="@Url.Action("Index", "Empleados")" class="btn btn-success">
            <i class="fas fa-backspace"></i>
            Volver
        </a>
    </div>
}

ViveroMVC02/Views/Empleados/Edit.cshtml
@model ViveroMVC02.ViewModels.Empleado.EmpleadoEditViewModels
@{ ViewBag.Title = "Edit"; }
<div class="container">
    <h2>Editar empleado</h2>
    <hr />
    @using (Html.BeginForm("Edit", "Empleados", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.EmpleadoId)
        <div class="form-group">
            @Html.LabelFor(m => m.Nombre)
            @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.Nombre, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Apellido)
            @Html.TextBoxFor(m => m.Apellido, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.Apellido, "", new { @class = "text-danger" })
        </div>
        @*<div class="row">*@
        <div class="col">
            <div class="form-group">
                @Html.LabelFor(m => m.NroDocumento)
                @Html.TextBoxFor(m => m.NroDocumento, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.NroDocumento, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Direccion)
                @Html.TextBoxFor(m => m.Direccion, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Direccion, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="col">
            <div class="form-group">
                @Html.LabelFor(m => m.TelefonoFijo)
                @Html.TextBoxFor(m => m.TelefonoFijo, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.TelefonoFijo, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.TelefonoMovil)
                @Html.TextBoxFor(m => m.TelefonoMovil, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.TelefonoMovil, "", new { @class = "text-danger" })
            </div>

        </div>
        @*</div>*@

        <div class="form-group">
            @Html.LabelFor(m => m.ProvinciaId)
            @Html.DropDownListFor(m => m.ProvinciaId, new SelectList(Model.Provincias, "ProvinciaId", "NombreProvincia"), "Seleccione Provincia", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Provincias, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.LocalidadId)
            @Html.DropDownListFor(m => m.LocalidadId, new SelectList(Model.Localidades, "LocalidadId", "NombreLocalidad"), "Seleccione Localidad", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.LocalidadId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.CorreoElectronico)
            @Html.TextBoxFor(m => m.CorreoElectronico, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CorreoElectronico, "", new { @class = "text-danger" })
        </div>


        <div class="form-group">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <a href="@Url.Action("Index", "Empleados")" class="btn btn-success">Volver</a>

        </div>}
</div>
@section scripts
 {
    <script>
        $(document).ready(function () {
            $("#ProvinciaId").change(function() {
                $("#LocalidadId").empty();
            });

            $("#ProvinciaId").change(function() {
                $("#LocalidadId").empty();
                $("#LocalidadId").append('<option value="0">[Seleccionar Localidad]</option>');

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetLocalidades")',
                    dataType: 'json',
                    data: {
                        ProvinciaId: $("#ProvinciaId").val()

                    },
                    success: function(Localidades) {
                        $.each(Localidades ,
                            function(i, localidad) {
                                $("#LocalidadId").append('<option value="' + localidad.LocalidadId + '">' + localidad.NombreLocalidad + '</option>');
                            });
                    },
                    error: function(ex) {
                        alert('Error al intentar cargar las Localidades.' + ex);
                    }
                });
                return false;
            });
        });

    </script>

}

ViveroMVC02/Views/Empleados/Index.cshtml
@model ViveroMVC02.ViewModels.Listador<ViveroMVC02.ViewModels.Empleado.EmpleadoListViewModels>

@{
    ViewBag.Title = "Index";
}

<div>
    <a href="@Url.Action("Create", "Empleados")" class="btn btn-primary" style="float: right">
        <i class="far fa-file-alt"></i>
        Nuevo
    </a>
    <h2>Lista de Empleados</h2>
    <hr />

</div>
@if (TempData["Msg"] != null)
{
    var msg = (string)TempData["Msg"];
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Éxito!</strong> @msg.
    </div>

}
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().Localidad)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Registros.First().Provincia)
            </th>

            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Registros.Any())
        {
            foreach (var item in Model.Registros)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Apellido)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Localidad)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Provincia)
                    </td>

                    <td>
                        <a href="@Url.Action("Edit","Empleados",new{id=item.EmpleadoId})" class="btn btn-warning"><i class="fas fa-edit"></i> Editar</a>
                        <a href="@Url.Action("Details","Empleados",new{id=item.EmpleadoId})" class="btn btn-info"><i class="fas fa-list"></i> Detalle</a>
                        <a href="@Url.Action("Delete", "Empleados", new {id = item.EmpleadoId})" class="btn btn-danger">
                            <i class="fas fa-trash-alt"></i> Borrar
                        </a>

                    </td>
                </tr>
            }

        }
        else
        {
            <tr>
                <td>No se agregaron Empleados todavía</td>
            </tr>
        }
    </tbody>
</table>
@if (Model.Registros.Any())
{
    <span>
        <strong>@Model.TotalRegistros</strong> registros encontrados
    </span>
    <span>&nbsp;|&nbsp;</span>
    <span>
        Página <strong>@(Model.PaginaActual)</strong> de
        <strong>@Model.TotalPaginas</strong>
    </span>
    <span>&nbsp;|&nbsp;</span>
}
else
{
    <span>No hay resultados para esta búsqueda</span>
    <span>&nbsp;|&nbsp;</span>
}

@if (Model.PaginaActual > 1)
{
    @Html.ActionLink("<<", "Index", new { pagina = 1 },
        new { @class = "btn btn-sm btn-secondary" })
    <span></span>
    @Html.ActionLink("Anterior", "Index", new { pagina = Model.PaginaActual - 1 },
        new { @class = "btn btn-sm btn-secondary" })
}
else
{
    @Html.ActionLink("<<", "Index", new { pagina = 1 },
        new { @class = "btn btn-sm btn-secondary disabled" })
    <span></span>
    @Html.ActionLink("Anterior", "Index", new { pagina = 1 },
        new { @class = "btn btn-sm btn-secondary disabled" })
}
<span></span>
@if (Model.PaginaActual < Model.TotalPaginas)
{
    @Html.ActionLink("Siguiente", "Index", new { pagina = Model.PaginaActual + 1 },
        new { @class = "btn btn-sm btn-secondary" })
    <span></span>
    @Html.ActionLink(">>", "Index", new { pagina = Model.TotalPaginas },
        new { @class = "btn btn-sm btn-secondary" })
}
else
{
    @Html.ActionLink("Siguiente", "Index", new { pagina = Model.TotalPaginas - 1 },
        new { @class = "btn btn-sm btn-secondary disabled" })
    <span></span>
    @Html.ActionLink(">>", "Index", new { pagina = Model.TotalPaginas },
        new { @class = "btn btn-sm btn-secondary disabled" })
}